config/routes.rb
Docfer::Application.routes.draw do

  devise_for :users

  root :to => 'home#home'

  resources :practices do
    resources :users
    resources :doctors, only:[:index], as: "doctors", controller: "users"
    resources :patients
    resources :connections, only:[:new, :create,:destroy,:index, :update]
  end

  resources :users, path: "doctors", only: [:show], as: "doctors", controller:"doctors" do
    resources :referrals, only:[:new,:create, :index,:show]
    resources :appointments, only:[:show,:index]
  end

  resources :practices do
    resources :patients do
      resources :practicememberships, only: [:new, :create]
    end
  end

  resources :practices do
    resources :appointments
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  ROLES = %w{practice_admin doctor}

  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :first_name, :last_name, :practice_id, :password, :password_confirmation, :remember_me
  after_initialize :default_values

  validates_presence_of :role, :email, :password



  validates :role, :inclusion => { :in => ROLES}

  belongs_to :practice
  has_many :appointments
  has_many :referrals
  has_many :received_referrals,
    class_name: 'Referral',
    foreign_key: 'to_user'

  before_save :default_values
  def default_values
    self.role ||= 'doctor'
  end

  def practice_admin?
    self.role == 'practice_admin'
  end

  def doctor?
    self.role == 'doctor'
  end

  def has_practice?
    practice.present?
  end

  def make_admin
    self.update_attribute(:role, 'practice_admin')
  end

  def full_name

    @name = "#{self.first_name} #{self.last_name}"
  end

  def received_referrals_from(practice)
    refs = received_referrals
    from_prac_doctor = refs.where(user_id: practice.user_ids)

  end

  def valid_referrals
    referrals.where("user_id IS NOT NULL")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #load_and_authorize_resource
  skip_authorize_resource :only => [:new, :create]

  def show
    @doctor = User.find(params[:id])

  end

  def index
    @practice = Practice.find(params[:practice_id])
    @doctors = @practice.users
  end

end

app/views/users/_appointments.html.erb
<h3>Appointments</h3>
<h5>Upcoming</h5>
<% if @doctor.appointments.count == 0 %>
  <p>No upcoming appointments at this time</p>
<% elsif current_user.role =='practice_admin' %>
  <table class="full_width centered">
    <tr>
      <th>Date</th>
      <th>Patient</th>
    </tr>
  <% @doctor.appointments.upcoming.each do |appointment| %>
    <tr>
      <td><%= appointment.date.strftime("%b %d,%y") %></td>
      <td><%= appointment.patient_name %></td>
    </tr>
    <% end %>
  </table>
<% end %><br />

<h5>Past</h5>
<% if @doctor.appointments.past.count == 0 %>
  <p>No old appointment records</p>
<% elsif current_user.role =='practice_admin' %>
  <table class="full_width centered">
    <tr>
      <th>Date</th>
      <th>Patient</th>
    </tr>
  <% @doctor.appointments.past.each do |appointment| %>
    <tr>
      <td><%= appointment.date.strftime("%b %d,%y") %></td>
      <td><%= appointment.patient_name %></td>
    </tr>
    <% end %>
  </table>
<% end %>

app/views/users/index.html.erb
<div class="large-7 columns">
  <h2 class="top-head"><%= "#{@practice.office_name} Doctors" %></h2>

    <% @doctors.each_slice(3) do |slice| %>

      <div class="row doc-divide">
        <% slice.each do |doc| %>
          <div class="large-4 columns">
            <p>Name: <%= doc.full_name %></p>
            <p>Email: <%= doc.email %></p>
            <p>Role: <%= doc.role %></p>
            <p><%= link_to 'Appointments', doctor_appointments_path(doc), remote: true %> </p>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="large-12 columns">
      <div id="doc-appoint-holder"></div>
    </div>
</div>
<div class="large-3 columns">
  <h5>Invite A Doc</h5>
  <%= link_to 'Email Invite', new_user_invitation_path %>



</div>

app/views/users/show.js.erb
$("#doc-appoint-holder").html(
  "<%= j(render :partial => 'users/appointments') %>");