config/routes.rb
Docfer::Application.routes.draw do

  devise_for :users

  root :to => 'home#home'

  resources :practices do
    resources :users
    resources :doctors, only:[:index], as: "doctors", controller: "users"
    resources :patients
    resources :connections, only:[:new, :create,:destroy,:index, :update]
  end

  resources :users, path: "doctors", only: [:show], as: "doctors", controller:"doctors" do
    resources :referrals, only:[:new,:create, :index,:show]
    resources :appointments, only:[:show,:index]
  end

  resources :practices do
    resources :patients do
      resources :practicememberships, only: [:new, :create]
    end
  end

  resources :practices do
    resources :appointments
  end

end

app/views/shared/_sideNav.html.erb
<div class="large-2 columns side-bor">
  <ul class="side-nav fix-nav">
    <li class="<%=(request.path == practice_path(current_practice)) ? "active" : "" %>">
      <%= link_to 'Practice', practice_path(current_practice) %>
    </li>
    <li class="<%=(request.path == practice_appointments_path(current_practice)) ? "active" : "" %>">
      <%= link_to 'Appointments', practice_appointments_path(current_practice) %>
    </li>
    <li class="<%=(request.path == practice_patients_path(current_practice)) ? "active" : "" %>">
      <%= link_to 'Patients', practice_patients_path(current_practice) %>
    </li>
    <li class="<%=(request.path == practice_connections_path(current_practice))? "active" : "" %>">
      <%= link_to 'Connections', practice_connections_path(current_practice) %>
    </li>
    <li class="<%=(request.path == practice_doctors_path(current_practice))? "active": "" %>">
      <%= link_to 'Doctors', practice_doctors_path(current_practice),:controller => :users, :action => :index %>
    </li>
    <li class="<%=(request.path == doctor_referrals_path(current_practice))? "active": "" %>">
      <%= link_to 'Referrals',doctor_referrals_path(current_practice) %>
    </li>
  </ul>

</div>

app/views/shared/_sideNavDoc.html.erb
<div class="large-2 columns bor">
  <ul class="side-nav fix-nav">
    <li class="active"><%= link_to 'Practice', practice_path(current_practice) %></li>
    <li><%= link_to 'Appointments', practice_appointments_path(current_practice) %></li>
    <li><%= link_to 'Referrals',doctor_referrals_path(current_practice) %></li>
  </ul>

</div>