config/routes.rb
Docfer::Application.routes.draw do

  devise_for :users

  root :to => 'home#home'

  resources :practices do
    resources :users
    resources :doctors, only:[:index], as: "doctors", controller: "users"
    resources :patients
    resources :connections, only:[:new, :create,:destroy,:index, :update]
  end

  resources :users, path: "doctors", only: [:show], as: "doctors", controller:"doctors" do
    resources :referrals, only:[:new,:create, :index,:show]
    resources :appointments, only:[:show,:index]
  end

  resources :practices do
    resources :patients do
      resources :practicememberships, only: [:new, :create]
    end
  end

  resources :practices do
    resources :appointments
  end

end

app/models/referral.rb
class Referral < ActiveRecord::Base
  attr_accessible :user_id, :notes, :patient_id, :status_type, :to_user
  after_initialize :default_values

  validates_presence_of :user_id
  validates_presence_of :patient_id
  validates_presence_of :status_type
  validates_presence_of :to_user

  belongs_to :user
  belongs_to :patient
  belongs_to :to_user_object,
    foreign_key: :to_user,
    class_name: "User"


  $REFERRAL_STATUS = ['Sent','Received']

  def default_values
    self.status_type ||= $REFERRAL_STATUS[0]
    self.notes ||= "No notes specified"

  end

  #Find all of the doctors for connected practices, filtering out docs from current practice
  def connected_docs

    @doctor = User.find(self.user_id)
    @practice = Practice.find(@doctor.practice_id)
    @connections = Connection.find(:all,
        :conditions =>["(requestor_id = ? OR target_id = ?) AND status_type = ?",
        @practice.id, @practice.id, "Accepted"])

    @connected_docs = []

    @connections.each do |connection|
      @connected_docs << User.find(:all,
        :conditions =>["(practice_id = ? OR practice_id = ?) AND practice_id != ?",
        connection.target_id,
        connection.requestor_id,
        @practice.id]) #this line removes current practice from query
    end
    #binding.pry

    @connected_docs.flatten.uniq

  end

  def involves?(user)
    #self.requestor_id == user.practice_id || self.target_id == user.practice_id
    user.practice.referrals.include?(self) || user.practice.received_referrals.include?(self)
  end



  def get_name(name = "user_id")
    #binding.pry
    if name == "user_id"
      @user = User.find(self.user_id)
    else
      @user = User.find(self.to_user)
    end
    @name = "#{@user.first_name} #{@user.last_name}"
  end

  def patient_name
    @record = PracticeMembership.where("patient_id = ? ", self.patient_id).first
    @patient = Patient.find(@record.patient_id)
    @name = "#{@patient.first_name} #{@patient.last_name}"

  end

  def receiving_practice_name
    @practice = self.user.practice.office_name

  end

  def senders_practice_name
    @practice = self.user.practice.office_name
  end

  def recipient_practice
    to_user_object.practice
  end

  def sender_practice
    User.find_by_id(user_id).practice

  end

  def created_at_month
    DateTime.parse(created_at).strftime("%B")

  end

  def self.sent_to_other_practice(practice)
    where(user_id: practice.user_ids)
  end

  def self.received_by_practice(practice)
    where(to_user: practice.user_ids)
  end


end

app/controllers/referrals_controller.rb
class ReferralsController < ApplicationController
  load_and_authorize_resource


  def new
    @doctor = User.find(params[:doctor_id])
    @referral = @doctor.referrals.build()
    @potential = User.all
    @patients = Patient.all
    @connected_docs = @referral.connected_docs
  end

  def create
    @doctor = User.find(params[:doctor_id])
    @to_doc = User.find(params[:referral][:to_user])
    @patient = Patient.find(params[:referral][:patient_id])
    @referral = @doctor.referrals.build(:to_user => @to_doc.id,
                                        :patient_id => @patient.id,
                                        :notes => params[:referral][:notes])

    if @referral.save
      redirect_to practice_path(@doctor.practice), notice: "Referral Sent"
    else
      render(action:'new')
    end

  end

  def show
    @referral = Referral.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def index

    @practice = current_user.practice
    if current_user.role == 'practice_admin'
      @referrals = @practice.valid_referrals
      @received = @practice.received_referrals
    else
      @referrals = current_user.valid_referrals
      @received = current_user.received_referrals

    end
    @doctor = current_user
    @referral = @doctor.referrals.build(params[:referral])
    @patients = @practice.patients
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: [@referrals,@received]}
    end
  end



end

app/views/referrals/_form.html.erb
<%= form_for [@doctor, @referral], :url => doctor_referrals_path(@doctor) do |f| %>

  <%= f.label :connected_doctors %>
  <%= f.collection_select :to_user, @referral.connected_docs, :id, :full_name, include_blank:true %><br /><br />
  <%= f.label :patients %>
  <%= f.collection_select :patient_id, @patients, :id, :full_name, include_blank: true %><br /><br />
  <%= f.label :notes %>
  <%= f.text_area :notes, :class=>"min-notes" %></br>

  <div class="row">
    <div class="small-7 small-centered columns">
      <%= f.submit "Send Referral", :class=>"tiny button" %>
    </div>
  </div>
<% end %>

app/views/referrals/_notes.html.erb
<h3>Notes</h3>
<% binding.pry %>
<p><%= sanitize referral %></p>

app/views/referrals/index.html.erb
<div class="large-7 columns">


  <h2 class="top-head">Referrals</h2>
  <div class="large-12 columns">
    <h3>Sent</h3>
    <% if @referrals.count == 0 %>
      <p>You haven't sent any referrals</p>
    <% elsif @referrals.count > 0 %>
    <table>
      <tr>
        <th>Sender</th>
        <th>To Practice</th>
        <th>Receiver</th>
        <th>Patient</th>
        <th>Date</th>
        <th>Notes</th>
      </tr>

      <% @referrals.each do |referral| %>

        <tr>
          <td><%= referral.get_name %></td>
          <td><%= referral.receiving_practice_name %></td>
          <td><%= referral.get_name("to_user") %></td>
          <td><%= referral.patient_name %></td>
          <td><%= referral.created_at.strftime("%b %d,%y") %></td>
          <td><%= link_to "Show", doctor_referral_path(current_user,referral), remote: true %>
        </tr>

      <% end %>

    </table>
    <% end %>
  </div>
  <div class="large-12 columns">
    <h3>Received</h3>
    <% if @received.count == 0 %>

      <p>No referrals have been received </p>
    <% elsif @received.count > 0 %>

    <table>
      <tr>
        <th>Receiver</th>
        <th>From Practice</th>
        <th>Sender</th>
        <th>Patient</th>
        <th>Date</th>
        <th>Notes</th>
      </tr>

      <% @received.each do |referral| %>
        <tr>
          <td><%= referral.get_name("to_user") %></td>
          <td><%= referral.senders_practice_name %></td>
          <td><%= referral.get_name %></td>
          <td><%= referral.patient_name %></td>
          <td><%= referral.created_at.strftime("%b %d,%y") %></td>
          <td><%= link_to "Show", doctor_referral_path(current_user,referral), remote: true %></td>
        </tr>

      <% end %>

    </table>
    <% end %>

  </div>

</div>
<div class="large-3 columns form-fixed">
  <% if current_user.role == 'doctor' %>
    <div class="large-12 columns">
      <h3>Send a Referral</h3>
      <%= render :partial => 'referrals/form' %>

    </div>
    <div id ="note-holder" class="large-12 columns note-holder-doc">
    </div>

  <% else %>

    <div id ="note-holder" class="large-12 columns">
    </div>
  <% end %>
</div>

app/views/referrals/new.html.erb
<H1>Send a Rerferral</h1>

  <%= render 'form' %>


  

app/views/referrals/show.js.erb
$("#note-holder").html("<h3>Notes</h3><br/><p><%= @referral.notes %></p>");