config/routes.rb
Docfer::Application.routes.draw do

  devise_for :users

  root :to => 'home#home'

  resources :practices do
    resources :users
    resources :doctors, only:[:index], as: "doctors", controller: "users"
    resources :patients
    resources :connections, only:[:new, :create,:destroy,:index, :update]
  end

  resources :users, path: "doctors", only: [:show], as: "doctors", controller:"doctors" do
    resources :referrals, only:[:new,:create, :index,:show]
    resources :appointments, only:[:show,:index]
  end

  resources :practices do
    resources :patients do
      resources :practicememberships, only: [:new, :create]
    end
  end

  resources :practices do
    resources :appointments
  end

end

app/models/practice.rb
class Practice < ActiveRecord::Base
  attr_accessible :contact_name, :email, :office_name, :phone, :users_attributes


  has_many :connections_as_requestor,
    class_name: 'Connection',
    foreign_key: 'requestor_id'

  has_many :connections_as_target,
    class_name: 'Connection',
    foreign_key: 'target_id'
  has_many :users
  has_many :admins,
    class_name: "User",
    conditions: { role: "practice_admin" }
  has_many :practice_memberships
  has_many :patients, :through => :practice_memberships
  has_many :appointments, :through => :users
  has_many :referrals, :through => :users
  has_many :received_referrals, :through => :users,
    class_name: 'Referral',
    foreign_key: 'to_user'

  validates_presence_of :office_name
  validates_presence_of :contact_name
  validates_presence_of :email
  validates_presence_of :phone

  validates_format_of :email, with: /@/
  accepts_nested_attributes_for :users

  def involves?(user)

    referrals.any? { |referral| referral.user == user }

  end


  def referrals_count(sent="to_user",timeframe = 365)

    @docs = User.where("practice_id = ?", self.id)
    @referrals = []
    @docs.each do |doc|
      @referrals << Referral.find(:all,:conditions =>["(#{sent} = ?)
        AND (created_at <= ? AND created_at >= ?)",
        doc.id,(Date.today+10.days), (Date.today-timeframe.days)])
    end
    @referrals.flatten
  end

  def involves?(user)
    self.id == user.practice_id
  end

  def all_practice_docs

    @docs = User.where("practice_id = ?", self.id)

  end
  #checks if patient is in practice
  def has_member?(patient)
    records = PracticeMembership.where("patient_id = ?", patient.id)
    records.pluck(:practice_id).include?(id)


  end

  def accepted_connections
    Connection.where("(requestor_id = ? OR target_id = ?) AND status_type = ?",self.id,self.id,"Accepted")

  end

  def pending_connections

     Connection.where("(requestor_id = ? OR target_id = ?) AND status_type = ?",self.id,self.id,"Pending")

  end

  def potential_connections
    self.class.joins("LEFT OUTER JOIN connections ON
      (practices.id = connections.target_id AND connections.requestor_id = #{self.id}) OR
      (practices.id = connections.requestor_id AND connections.target_id = #{self.id})").
      where('connections.id IS NULL')

  end

  #Filter out nil referrals created on the index page
  def valid_referrals
    referrals.where("user_id IS NOT NULL")
  end

  def most_sent_referrals
    refs = users.each_with_object({}) do |user, hash|
      hash[user.id] = user.referrals.group_by_month("created_at").count
    end

    refs.reject!{|k,v| v == {}}
    if (refs.length == 0)
       "Not Applicable"
    else
      record = Hash[refs.sort_by {|user_id, date_counts| date_counts.values.max }.reverse!].first

      user = User.find(record[0]).full_name
      count = record[1].sort_by{|k,v| k}.last.last
      stat = "#{user} - #{count}"
    end

  end
  def most_received_referrals
    refs = users.each_with_object({}) do |user, hash|
      hash[user.id] = user.received_referrals.group_by_month("created_at").count
    end
    refs.reject!{|k,v| v == {}}
    if (refs.length == 0)
       "Not Applicable"
    else
      record = Hash[refs.sort_by {|user_id, date_counts| date_counts.values.max }.reverse!].first
      user = User.find(record[0]).full_name
      count = record[1].sort_by{|k,v| k}.last.last
      stat = "#{user} - #{count}"
    end

  end

  def sender_practices
    senders = User.find(received_referrals.pluck(:user_id))
    pracs = []
    senders.each do |user|
      pracs << user.practice_id
    end
    pracs.collect{|prac| Practice.find(prac)}.uniq

  end

  #Get the practice who has sent you the most referrals this month
  def most_inbound
    inbound = Hash.new
    data = sender_practices.map do |sender|
      if sender.referrals.count == 0
        next
      end
      inbound[sender.office_name] = sender.referrals.received_by_practice(self).group_by_month("referrals.created_at").count
    end
    if (data.length == 0)
       "Not Applicable"
    else
      record = inbound.max_by{|k,v| v.max_by{|k1,v1| [k1,v1]}}
      prac = record[0]
      count = record[1].sort_by{|k,v| k}.last.last

      stat = "#{prac} - #{count}"
    end
  end

  #retrieves all practcememberhsips to be iterated through
  def referred_appointments(opt)
    patients = []
    memberships= []
    opt.each do |ref|
      patients << ref.patient_id
    end

    patients.each do |pat|
      memberships << PracticeMembership.where("(patient_id = ? AND practice_id = ?)",pat,self)
    end
    memberships.flatten.uniq

  end

  def referral_appointments(opt)
    range = Time.now.beginning_of_month..Time.now.end_of_month
    referrals = Hash.new
    data = referred_appointments(opt).map do |member|
      if member.appointments.count == 0
        next
      end
      referrals[member.id] = member.appointments.from_practice(member.practice).group_by_month("appointments.created_at", Time.zone, range).count
    end
    referrals.delete_if{|k,v| v.empty?}
    sum = 0
    referrals.values.each do |x|
      sum += x.values[0]
    end
    sum

  end

  def referral_to_appointment_percent(opt)

    received = (referral_appointments(opt)).to_f
    total = appointments.group_by_month("appointments.created_at").count.values[-1].to_f
    percent = ((received/total) *100).to_s[0..3]

  end

  #gets all practice patients and ones who have been referred but haven't set up an appointment
  def all_patients
    pats = patients.pluck(:id)
    ref_pats = received_referrals.pluck(:patient_id).uniq
    Patient.find_all_by_id((pats + ref_pats).uniq)

  end


  def self.practices_that_sent_referrals_to(practice)
    Referral.where(to_user: Practice.user_ids).practices
  end


  def merge_individual_refs_to_practice(data)
    totals ={}
    data.each do |user|
      practice_name = user[:name]
      totals[practice_name] ||= Hash.new(0)

      months = user[:data]

      months.each do |month, count|
        totals[practice_name][month] += count
      end
    end

    totals.map{|k,v| {:name => k, :data => v }}
  end

  def receivers
    User.find(referrals.pluck(:to_user))
  end

  def sent_monthly_referrals
    data = receivers.map do |receiver|
      {:name => receiver.practice.office_name, :data => hash_fix(receiver.received_referrals_from(self).group_by_month(:created_at).count) }
    end
    #binding.pry
    merge_individual_refs_to_practice(data)
  end

  def senders
    User.find(received_referrals.pluck(:user_id))
  end

  def monthly_referrals
    data = senders.map do |sender|
      {:name => sender.practice.office_name, :data => hash_fix(sender.referrals.group_by_month(:created_at).count) }
    end
    merge_individual_refs_to_practice(data)
  end


  def hash_fix(thing)
    h = {}
    thing.each do |k,v|
      h[DateTime.parse(k).strftime("%B")] = v
    end
    h
  end




end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  load_and_authorize_resource
   #skip_authorize_resource :only => [:new, :create]
   skip_before_filter :check_user_has_practice!, :only =>[:new,:create,:show]

   helper_method :monthly_referrals

  def new
    @practice = Practice.new()
  end

  def create
    @practice = Practice.new(params[:practice])
    @user = current_user
    if @practice.save
      @user.practice_id = @practice.id
      @user.make_admin
      @user.save

     redirect_to @practice, notice:"Practice Created"
    else
      render 'new'
    end
  end

  def show
    @practice = current_user.practice
    @sent = @practice.sent_monthly_referrals
    @received = @practice.monthly_referrals
    @stats = {
      most_sent_referrals: @practice.most_sent_referrals,
      most_received_referrals: @practice.most_received_referrals,
      most_inbound_referrals: @practice.most_inbound,
      referral_appointments: @practice.referral_appointments(@practice.received_referrals),
      referral_to_appointment_percent: @practice.referral_to_appointment_percent(@practice.received_referrals),
      sent_referral_to_appointment_percent: @practice.referral_to_appointment_percent(@practice.referrals)
    }
  end


end

app/views/practices/_form.html.erb
  <%= form_for(@practice) do |f| %>

    <% if @practice.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :office_name %>
    <%= f.text_field :office_name %><br />

    <%= f.label :contact_name %>
    <%= f.text_field :contact_name %><br />

    <%= f.label :phone %>
    <%= f.text_field :phone %>

    <%= f.label :email %>
    <%= f.text_field :email %>

     <%= f.submit :class=> "button" %>

  <% end %>

app/views/practices/_sent.html.erb
<div id="chart">
  <%= column_chart sent_monthly_referrals %>
</div>

app/views/practices/new.html.erb
<div class="large-12 columns">
  <div class="small-6 large-centered columns">
    <h1>New Practice</h1>
    <%= render 'form' %>

    <%= link_to 'Back', practices_path %>
  </div>
</div>

app/views/practices/show.html.erb
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

  <div class="large-10 columns">
    <h2 class="top-head"><%= @practice.office_name %></h2>
    <div class="large-12 columns bor-bottom">
      <h3 class="">This Month</h3>
      <div class="large-6 columns">
        <p>Most Sent Referrals: <span><%= @stats[:most_sent_referrals] %></span> </p>
        <p>Most Received Referrals: <span><%= @stats[:most_received_referrals]%></span></p>
        <p>Most Inbound Referrals: <span><%= @stats[:most_inbound_referrals] %></span></p>
      </div>
      <div class="large-6 columns">
        <p>Referral Appointments:<span> <%= @stats[:referral_appointments] %> </span></p>
        <p>Received Referral to Appointment: <span><%= @stats[:referral_to_appointment_percent] %>%</span></p>
        <p>Sent Referral to Apppointment:<span> <%= @stats[:sent_referral_to_appointment_percent]%>%</span></p>
      </div>

    </div>


    <div id="chart">
      <h4 class="extra-pad">Referrals</h4>
      <h5>Received - <%= @practice.received_referrals.count %></h5>

      <%= column_chart @received %>

       <%#= column_chart @practice.received_referrals.group(:user_id).group_by_month("referrals.created_at").count %>
      <h5>Sent - <%= @practice.referrals.count %></h5>
      <%= column_chart @sent %>


    </div>

  </div>

<%= content_for :extra_footer do %>

<% end %>




<!--      //# = column_chart @practice.received_referrals.group_by_month("referrals.created_at").count.map{|x,y|
     //#    {x.sender_practice => y}} %> -->